import Link from "next/link";

export default function WorkPage() {
  const projects = [
    {
      n: "01",
      title: "Series A Pitch — FinStack",
      category: "Fintech",
      desc: "Complete investor pitch deck with financial projections, market sizing, and competitive landscape for a B2B payments infrastructure startup.",
    },
    {
      n: "02",
      title: "Seed Round — GreenLoop",
      category: "Climate Tech",
      desc: "Sustainability-focused pitch with ESG metrics, carbon offset modeling, and impact investor positioning.",
    },
    {
      n: "03",
      title: "Pre-Seed — MedAI",
      category: "Healthcare",
      desc: "FDA pathway analysis, clinical trial roadmap, and TAM breakdown for an AI-powered diagnostics platform.",
    },
    {
      n: "04",
      title: "Bridge Round — Nomad",
      category: "Remote Work",
      desc: "Growth metrics dashboard, cohort analysis, and expansion strategy for a distributed team management tool.",
    },
    {
      n: "05",
      title: "Series B — DataForge",
      category: "Enterprise SaaS",
      desc: "Enterprise sales pipeline modeling, ARR projections, and competitive moat analysis for a data orchestration platform.",
    },
    {
      n: "06",
      title: "Seed Round — EduPath",
      category: "EdTech",
      desc: "User engagement analytics, curriculum mapping, and partnership strategy for an AI tutoring platform.",
    },
  ];

  return (
    <div className="min-h-screen bg-white text-black">
      {/* ═══ NAVIGATION ═══ */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-white border-b hairline-dark">
        <div className="flex items-center h-[72px] w-full">
          <div
            className="flex items-center h-full border-r hairline-dark flex-shrink-0"
            style={{ padding: "0 clamp(24px, 3vw, 56px)" }}
          >
            <Link href="/" className="text-[22px] font-black tracking-tight whitespace-nowrap">
              TRACTION<span className="text-accent">.</span>
            </Link>
          </div>
          <div className="hidden md:flex flex-1 items-center justify-center h-full">
            <div className="flex items-center h-full" style={{ gap: "clamp(48px, 6vw, 96px)" }}>
              <Link href="/work" className="swiss-label text-black h-full flex items-center">
                Work
              </Link>
              <Link href="/services" className="swiss-label text-gray-300 hover:text-black transition-colors h-full flex items-center">
                Services
              </Link>
              <Link href="/login" className="swiss-label text-gray-300 hover:text-black transition-colors h-full flex items-center">
                Log In
              </Link>
            </div>
          </div>
          <div className="hidden md:flex items-center h-full flex-shrink-0 border-l hairline-dark">
            <Link
              href="/signup"
              className="flex items-center h-full bg-black text-white swiss-label hover:bg-gray-400 transition-colors whitespace-nowrap"
              style={{ padding: "0 clamp(32px, 3vw, 64px)" }}
            >
              Start Project&ensp;&rarr;
            </Link>
          </div>
        </div>
      </nav>

      {/* ═══ HERO ═══ */}
      <section
        className="pt-[72px]"
        style={{ padding: "clamp(120px, 12vw, 200px) clamp(48px, 6vw, 120px) clamp(64px, 8vw, 128px)" }}
      >
        <p className="swiss-label text-gray-200 animate-fade-up" style={{ marginBottom: "32px" }}>
          Selected Work
        </p>
        <h1 className="text-display font-black uppercase tracking-tight leading-[0.92] animate-fade-up delay-1">
          Pitches we&apos;ve
          <br />
          helped build.
        </h1>
        <p
          className="text-body-lg text-gray-300 max-w-[560px] leading-relaxed animate-fade-up delay-2"
          style={{ marginTop: "clamp(24px, 3vw, 48px)" }}
        >
          Every deck generated by Traction is unique — built from your idea,
          shaped by data, and designed to convince.
        </p>
      </section>

      {/* ═══ PROJECT GRID ═══ */}
      <section className="border-t hairline-dark">
        <div style={{ padding: "clamp(64px, 8vw, 120px) clamp(48px, 6vw, 120px)" }}>
          <div
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3"
            style={{ columnGap: "clamp(40px, 5vw, 80px)", rowGap: "clamp(56px, 6vw, 96px)" }}
          >
            {projects.map((p) => (
              <div key={p.n} className="group">
                {/* Placeholder thumbnail */}
                <div
                  className="w-full bg-gray-100 border hairline-dark mb-8 flex items-end justify-between"
                  style={{ aspectRatio: "4 / 3", padding: "24px" }}
                >
                  <span className="text-[11px] font-mono text-gray-200">{p.n}</span>
                  <span className="swiss-label text-gray-200">{p.category}</span>
                </div>
                <h3 className="text-[20px] font-bold leading-snug" style={{ marginBottom: "12px" }}>
                  {p.title}
                </h3>
                <p className="text-body-sm text-gray-300 leading-relaxed">
                  {p.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ FOOTER ═══ */}
      <footer className="bg-black text-white">
        <div style={{ padding: "clamp(64px, 8vw, 120px) clamp(48px, 6vw, 120px) clamp(48px, 6vw, 80px)" }}>
          <h2 className="text-display-lg font-black uppercase tracking-tight leading-[0.88]">
            Your idea
            <br />
            is next.
          </h2>
          <div style={{ marginTop: "clamp(40px, 5vw, 64px)" }}>
            <Link
              href="/signup"
              className="group inline-flex items-center border border-white/30 text-white font-bold uppercase tracking-[0.12em] hover:bg-white hover:text-black transition-colors"
              style={{ padding: "24px 48px", fontSize: "15px" }}
            >
              Start Your Pitch
              <span className="inline-block ml-6 transition-transform group-hover:translate-x-1" style={{ fontSize: "20px" }}>
                &rarr;
              </span>
            </Link>
          </div>
          <div
            className="flex flex-col md:flex-row md:items-end md:justify-between pt-10 border-t border-white/20"
            style={{ marginTop: "clamp(64px, 8vw, 120px)" }}
          >
            <Link
              href="mailto:hello@traction.ai"
              className="text-body font-medium underline underline-offset-4 decoration-white/40 hover:decoration-white transition-colors"
            >
              hello@traction.ai
            </Link>
            <div className="mt-8 md:mt-0" style={{ display: "flex", gap: "clamp(24px, 3vw, 48px)" }}>
              <span className="swiss-label text-white/50">&copy; 2026 Traction</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
